  node:
      image: "node:8"
      user: "node"
      working_dir: /home/node/app
      environment:
        - NODE_ENV=production
      volumes:
        - ../:/home/node/app
      expose:
        - "8081"
      command: bash -c "npm install && npm run dev"
